# General Settings
title: "wafer.space - Budget silicon manufacturing"
email: "info@wafer.space"
#email_2: "support@tortoizthemes.com"
description: >- # this means to ignore newlines until "baseurl:"
  Budget silicon manufacturing.
favicon: "favicon.png"

# Seo Meta Settings
# meta_og_image: "assets/images/meta-image.webp"
# meta_twitter_image: "assets/images/meta-image.webp"

# Site Wide Theme Color Setting
color_scheme: sky #Aqua Blue Brown Cobalt Green Hibiscus Leaf Meander Orange Pink Purple Red Rose Sky Teal Violet Yellow

# Site Wide Theme Font Setting
font_scheme:  # Jost, Nunito , DM Sans + Zilla Slab , HK Grotesk, Abhaya, Libre

# Sitewide Logo
black_logo_1x: "assets/images/logo.webp"
black_logo_2x: "assets/images/logo@2x.webp"
light_logo_1x: "assets/images/logo-light.webp"
light_logo_2x: "assets/images/logo-light@2x.webp"

# Site Wide Address and Phone Number
address_01: '143&nbsp;Cecil&nbsp;Street,<br />#17&#8209;04,&nbsp;GB&nbsp;Building,<br />Singapore 069542'
phone_number: # "+00 (123) 456 78 90"

# Site Wide Copyright
copyright_text: "© 2025 Wafer Space PTE. LTD. All rights reserved."

# Site Wide Google Analytics
google_analytics:
  enable: true
  type: gtag
  key: "G-1JB9VZY864" # UA-351909305-1"  # UA-664136761-1

# Site Wide Google Map
google_map: |
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3172.4564967931838!2d-122.03250858386237!3d37.33169997984258!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fb5b6e94ffe23%3A0x63bb79532baa6af4!2sApple+Campus!5e0!3m2!1sen!2str!4v1553850783971!5m2!1sen!2str" style="width:100%; height: 100%; border:0" allowfullscreen=""></iframe>

# Site Wide Social Accounts
#social_accounts:
#  title: "Follow Us"
#  links:
#    - url: "#"
#      icon: "jam jam-twitter"
#
#    - url: "#"
#      icon: "jam jam-facebook"
#
#    - url: "#"
#      icon: "jam jam-instagram"
#
#    - url: "#"
#      icon: "jam jam-vimeo"
#
#    - url: "#"
#      icon: "jam jam-youtube"

# Site Wide External Links for footer
external_links:
  title: "More"
  links:
    - url: "/"
      text: "Home"
    - url: "/about.html"
      text: "About"
    - url: "/design-help.html"
      text: "Design Help"
    - url: "/news"
      text: "News"
    - url: "/how.html"
      text: "How"
    - url: "/help.html"
      text: "Help"
    - url: "/faq.html"
      text: "FAQ"

# Site Wide External Links for footer
#external_links_02:
#  title: "&nbsp;"
#  links:
#    - url: "/how/"
#      text: "How"
#    - url: "/help/"
#      text: "Help"
#    - url: "#"
#      text: "Contact Us"
#    - url: "#"
#      text: "Terms of Use"
#    - url: "#"
#      text: "Privacy Policy"

# Site Wide External Links for footer
#external_links_03:
#  title: "Company"
#  links:
#    - url: "#"
#      text: "Our Team"
#    - url: "#"
#      text: "Strategy"
#    - url: "#"
#      text: "Service"
#    - url: "#"
#      text: "Mission"
#    - url: "#"
#      text: "Process"

# Footer Newsletter
footer_newsletter:
  title: "Get Notified!"
  sub_title: "Sign up to be notified when more information is available"
  subscribe_button_text: "Join"

# Author Page Background Image
author_page_header:
  header_background_image: "assets/images/art/bg31.webp"

# Gallery
gallery:
  images:
  - img: "assets/images/art/z1.svg"
  - img: "assets/images/art/z2.svg"
  - img: "assets/images/art/z3.svg"
  - img: "assets/images/art/z4.svg"
  - img: "assets/images/art/z5.svg"
  - img: "assets/images/art/z6.svg"
  - img: "assets/images/art/z7.svg"
  - img: "assets/images/art/z8.svg"
